/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include<stdio.h>


#define FIBMAX 4000000

int main()
{
	long long int sum_even_fibs = 0, sum = 0, i, a = 0, b = 1;
	
	while(a < FIBMAX)
	  {
	    printf("%d",a);
		if (a  & 	01){
			//odd
		}
		else
		{
			sum_even_fibs += a;
			printf(" -- even sum = %d", sum_even_fibs);
		}
		printf("\n");
	    sum = a + b;
	    a = b;
	    b = sum;
		
	  }
	
	
	// do fibonacci
	
	return 0;
}

long long int fibonacci(long long int x) 
{
	if (x==0) 
		return 0; 
	else if (x==1) 
		return 1; 
	else 
		return fibonacci(x-1)+fibonacci(x-2); 
}